### ISSUE TITLE
Make a plan to roll out new API

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/av-control-api#93]

**Comment by dannyrandall** [comment]
So obviously the biggest issue we are going to run into deploying the new API is that any service that currently consumes it will need to be modified. Here's what we'll need to do:
- Update [the UI](https://github.com/byuoitav/ui), but only the backend
  - this service will also have to change to parse the "compiled output" from [shipyard](github.com/byuoitav/shipyard)
  - the ui will also be the piece that is sending room state events (along with the [DMM](github.com/byuoitav/device-monitoring))
- Update the bits of the DMM that use the API
  - active signal
  - the 5 minute "true up", although this _may_ make more sense to be in the ui
- The uapi translator (may not actually be doing state right now, I can't remember)
- A translation script to take old rooms and configure them for the new API/shipyard config
  - I think this is an ideal time to transition off of the old couch instances (in the old AWS account) and move to whatever we are going to - couch in k8s, mongo, etc. It would also make sense to figure out how we want to do offline caching of documents for all of the above services (including the API) at the same time.

All of this will have to be done before we can actually deploy/use the new API.

Thoughts? @danielwells @bwinterton @thailandmatt

**Comment by bwinterton** [comment]
I agree with everything you've said and wanted to add some information:
* The UAPI is currently doing state and does call the API under the covers so it will have to be updated to talk to the new api. 
* The UAPI also currently reads the UI config in order to determine "logical" displays in the room. This will have to be updated as well to parse the new room-config 
* As part of the translation scripts, we will have to move everything into the new formats, and then we will want shipyard to run through all of the rooms to compile the API control doc and room config for each room. 
* The DMM will also have to be updated to read the shipyard documents out of couch.
  * Danny and I have had a discussion about the DMM and we have decided that the easiest way forward is for the AV Control API to be able to run the health checks when requested (as the drivers will all be built into the same binary). This means the DMM will have to be changed to ping devices on it's own, but then request their health status from the AV Control API

I also agree that I think this is an excellent time to address the new caching layout on the pis and work towards replacing couch on the pis with a better caching system.
